# Generated by Django 3.0.7 on 2020-06-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasta',
            new_name='Pastas',
        ),
        migrations.RenameModel(
            old_name='Salad',
            new_name='Salads',
        ),
        migrations.RenameModel(
            old_name='Sub',
            new_name='Subs',
        ),
    ]
