# Generated by Django 3.0.7 on 2020-06-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200611_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='platters',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subtoppings',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
    ]
