# Generated by Django 3.0.7 on 2020-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200611_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizzas',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizzas',
            name='pizzatype',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1 Topping', '1 Topping'), ('2 Topping', '2 Topping'), ('3 Topping', '3 Topping'), ('Special', 'Special')], default='Delete', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzas',
            name='version',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Delete', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='platters',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subtoppings',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5),
        ),
    ]
