# Generated by Django 3.0.7 on 2020-06-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200612_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.PizzaToppings'),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='platters',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subtoppings',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5),
        ),
    ]
