# Generated by Django 3.0.7 on 2020-06-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200612_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.SubToppings'),
        ),
    ]
