# Generated by Django 3.0.7 on 2020-06-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='PREP', max_length=30),
        ),
    ]
